#' Pivots date column names into one colum
#'
#' @param data A dataframe with data columns
#' @param date_format A regular expression to detect the date columns (default value matches DD/MM/YYY); works with dplyr's 'matches' function to select date columns)
#'
#' @return A dataframe in a long format (containing a new date column)
#'
pivot_longer_by_date <- function(data, date_format = "\\d+\\/\\d+\\/\\d+") {
  data %>%
    tidyr::pivot_longer(cols = dplyr::matches(date_format), names_to = "date") %>%

    dplyr::mutate_at("date", lubridate::mdy)
}

#' Rename state and country column
#'
#' Replace clumsy column names with accessable names
#'
#' @param data A dataframe with columnames `Country/Region` and `Province/State`
#'
#' @return A long dataframe (with two renamed colums)
#'
rename_corona_data <- function(data) {
  data %>%
    dplyr::rename(country = `Country/Region`, state = `Province/State`)
}

#' Add day column to dataframe (grouped for each country and state)
#'
#' Day column where day = 1 corresponds to the first date with at least n `number_of_cases`
#'
#' @param data A dataframe (suits with dataframe generated by \code{read_corona()})
#' @param number_of_cases Defaul value: 100, Integer, indicating the minimum number of cases (infections/ deaths/ recovered)
#'
#' @return A dataframe (with an additional day colum as incremental integers starting at 1)
#'
#' @examples \dontrun{
#' data <- read_corona()
#' data %>% create_day_sequence()
#' }
#'
create_day_sequence <- function(data, number_of_cases = 100) {
  data %>%
    dplyr::group_by(country, state) %>%
    dplyr::filter(value >= 100) %>%
    dplyr::arrange(country, state, date) %>%
    dplyr::mutate(day = 1) %>%
    dplyr::mutate(day = cumsum(day))
}

#' Filter dataframe for at least n cases per group
#'
#' The function computes the number of values for each group (e.g. country) and filters out those with less than the specified number of values.
#' It is recommended to first group the dataframe for the stata the number of values have to be evaluated (e.g. at least 10 values in a country)
#'
#' @param data Dataframe (containing a day column)
#' @param min_n_days Integer How many values must be available at least for each group
#'
#' @return A dataframe
filter_min_days <- function(data, min_n_days = 5) {
  data %>%
    mutate(n_days = max(day)) %>%
    filter(n_days >= min_n_days) %>%
    select(-n_days)
}
